server:
  servlet:
    context-path: /api/v1/

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  application:
    name: "bookshelf"

springdoc:
  default-produces-media-type: application/json
