server:
  servlet:
    context-path: /api/v1/

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  application:
    name: "bookshelf"

springdoc:
  default-produces-media-type: application/json
