server:
  port: 8088

spring:
  datasource:
    platform: postgres
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
      login-url: http://localhost:4200/login
  file:
    uploads:
      photos-output-path: ./uploads

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
